---
- name: Desplegar contenedor sencillo en Ubuntu
  hosts: all
  become: yes

  vars:
    container_name: "mi_contenedor"
    container_image: "nginx:latest"
    container_port: 80

  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Iniciar Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Descargar imagen de Docker
      docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Crear y ejecutar contenedor
      docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        ports:
          - "{{ container_port }}:80"
        state: started
        restart: unless-stopped
