---
- name: Playbook para instalación de software en Ubuntu Server
  hosts: all  # Define el nombre del grupo de hosts en tu archivo de inventario
  become: true
  become_method: sudo
  become_user: root

  vars:
    mysql_root_password: "juan"  # Define la contraseña de root para MySQL
    postgresql_user: "postgres"
    postgresql_password: "juan"
    zabbix_repo: "http://repo.zabbix.com/zabbix/6.0/ubuntu {{ ansible_distribution_release }} main"
    grafana_repo: "https://packages.grafana.com/oss/deb stable main"

  tasks:
    - name: Actualizar los repositorios de apt y paquetes del sistema
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Instalar prerrequisitos generales
      apt:
        name: 
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    # --- INSTALACIÓN DE MYSQL ---
    - name: Instalar MySQL y configurar root password
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password"
        value: "{{ mysql_root_password }}"
        vtype: "password"
        
    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Asegurar MySQL esté en ejecución
      service:
        name: mysql
        state: started
        enabled: true


    # --- INSTALACIÓN DE APACHE ---
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Asegurar Apache esté en ejecución
      service:
        name: apache2
        state: started
        enabled: true

    # --- INSTALACIÓN DE ZABBIX ---
    - name: Agregar repositorio de Zabbix
      apt_repository:
        repo: "{{ zabbix_repo }}"
        state: present

    - name: Instalar Zabbix Server y Zabbix Agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-agent
        state: present

    - name: Asegurar Zabbix esté en ejecución
      service:
        name: zabbix-server
        state: started
        enabled: true


