---
- name: Update and upgrade Ubuntu system
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot the server if needed
      reboot:
        msg: "Reboot initiated by Ansible if required"
        reboot_timeout: 600
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"
